acid-rain: true
acid-water: true
acid-rain-time(s): 600
acid-rain-load(s): 300

effects:
 - 19
 - 20
 - 18
 - 17
 - 15
 - 2
 - 4
 - 9

rain-worlds:
 - "zc"

water-worlds:
 - "zc"

effect-duration: 5
effect-amplifier: 1
effect-visible: true
